CC = {{compiler}}
CFLAGS = -g -w -lm -gencode arch=compute_70,code=sm_70

SRC = {{#source_files}} {{.}} {{/source_files}}
HEADERS = {{#header_files}} {{.}} {{/header_files}}
OBJ = $(SRC:.cc=.o)
EXEC = {{bin_name}}

all: $(EXEC)

$(EXEC): $(OBJ) $(HEADERS)
	$(CC) $(LDFLAGS)  -o $@ $(OBJ) $(LBLIBS) $(CFLAGS)

clean:
	rm $(EXEC)
